{% set name = "facadedevice" %}
{% set version = "1.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/facadedevice-{{ version }}.tar.gz
  sha256: 0b8a4d11eb56d4eb4384026908259cb3f7e36e45b84430cc245b94946a05b36d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools-scm
  run:
    - python >={{ python_min }}
    - pytango >=9.2.1
    - numpy >=1.8

test:
  imports:
    - facadedevice
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://gitlab.com/MaxIV/tango-facadedevice
  summary: Provide a descriptive interface for reactive high-level Tango devices.
  license: GPL-3.0-or-later
  license_file: LICENSE.txt
  doc_url: https://tango-facadedevice.readthedocs.io/
  dev_url: https://gitlab.com/MaxIV/tango-facadedevice

extra:
  recipe-maintainers:
    - beenje
